name: hutton-technologies
region: nyc

services:
  # Backend API
  - name: api
    source:
      repo: https://github.com/YOUR_USERNAME/hutton-technologies
      branch: main
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: CORS_ORIGINS
        value: https://huttontechnologies.com,https://www.huttontechnologies.com

  # Frontend
  - name: web
    source:
      repo: https://github.com/YOUR_USERNAME/hutton-technologies
      branch: main
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${api.PUBLIC_URL}

domains:
  - domain: huttontechnologies.com
    type: PRIMARY
  - domain: www.huttontechnologies.com
    type: ALIAS
